import {ProjectInfo} from "@/types/project-info-list";

export const projectInfo: ProjectInfo = {
    title: "DSPDA - Digital Spatial Profiling Data Analysis Software",
    description: "DSPDA is a software tool developed in collaboration " +
        "with NanoString Corp. and Seattle BioSoftware. It supports " +
        "the analysis of spatial profiling data generated by advanced " +
        "microscopy systems, enabling researchers to efficiently " +
        "process and interpret high-resolution molecular data.",
    footer: "DSPDA provides researchers with a reliable framework for " +
        "conducting spatial analyses, enhancing the interpretation of " +
        "microscopy data in biological and clinical research",
    projectSections: [
        {
            title: "Key Features",
            list: [
                {
                    title: "Spatial Data Analysis",
                    description: "Enables visualization and quantification " +
                        "of data at single-cell resolution, allowing detailed " +
                        "exploration of molecular distributions within tissues."
                },
                {
                    title: "Streamlined Workflow",
                    description: "Includes tools for image processing, region of interest " +
                        "(ROI) selection, and spatial data profiling, simplifying complex workflows."
                },
                {
                    title: "Optimized Integration",
                    description: "Designed to work seamlessly with NanoString’s " +
                        "spatial profiling microscopes, ensuring compatibility and ease of use."
                }
            ]
        },
        {
            title: "Application",
            list: [
                {
                    description: "Profiling RNA and protein expression in tissue samples."
                },
                {
                    description: "Exploring spatial relationships between " +
                        "biomolecules and cellular structures."
                },
                {
                    description: "Supporting biomarker discovery and translational research."
                }
            ]
        },
        {
            title: "Contribution",
            description: "Our team’s work on DSPDA focused on:",
            list: [
                {
                    description: "Developing analytical features to process spatial profiling " +
                        "data, with a focus on creating clear and actionable results."
                },
                {
                    description: "Building tools for graphing and visualizing analysis outcomes, " +
                        "and ensuring these can be exported easily for further use."
                },
                {
                    description: "Creating reporting features to help users compile results into " +
                        "structured and customizable reports that meet various research needs"
                }
            ]
        }
    ]
}
